### PR TITLE
adds Mayer's data for the libration of the moon and Laplace's data fo…

### PR DESCRIPTION
**Pull request by lfpdroubi**
…r the Saturn motion analysis.

### CODE REVIEW

**Comment by friendly** [comment]
This looks good to me. Thanks very much  Have you run R CMD check on your fork with this commit?

HistData v 0.8-7 was just accepted on CRAN, so I'll have to bump the version before I deal with this pull request.

**Comment by lfpdroubi** [comment]
Yes, Mr. Friendly. Just did it again to be sure, and everything is fine (no errors nor warnings or notes).  I think this is the right place to make this data available. Thank you!

**Comment by friendly** [comment]
Yes again. thanks so much for your contribution.  I will acknowledge you in the next update to the package, but this will take a few days.

**Comment by friendly** [comment]
Hi Luiz @lfpdroubi 
Thanks again for your contribution.  I enjoyed reading your description of the historical context

I merged your Meyer & Saturn data into the pre-release of HistData.  I also made you a package contributor ("ctb") in the Authors@R

**Pull request merged**
